version: "2"
services:
  service:
    build: .
    image: pwn150
    ports:
      - 9999:10000
    volumes:
      - "$PWD/flag:/pwn/flag"
    tty: true
    networks:
      - net

networks:
  net:
    external:
      name: h1ve_frp_containers