version: "2"
services:
  service:
    build: .
    image: pilot
    ports:
      - 9999:10000
    volumes:
      - "$PWD/flag:/flag.txt"
    tty: true
    networks:
      - net

networks:
  net:
    external:
      name: h1ve_frp_containers